{
 "title": "Node Detail",
 "tags": [
  "monitoring",
  "node",
  "scut"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(up{job=~\".*-node\"}, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=~\"$job\"}",
     "legendFormat": "{{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Node CPU Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Resident Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}